package hattmakarn;

import java.time.LocalDate;
import hattmakarn.Connector;
import hattmakarn.PlaneringsYta;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author theod
 */
public class FörsäljningsStatistik extends javax.swing.JFrame {
    private static InfDB idb;

    /**
     * Creates new form FörsäljningsStatistik
     */
    public FörsäljningsStatistik() {
        initComponents();
        
        try {
           idb = new InfDB("hattdb", "3306", "hattdba", "hattkey");
        } catch (InfException ex) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfTelefon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        knappSök = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taKundStatistik = new javax.swing.JTextArea();
        tfStartDatum = new javax.swing.JTextField();
        tfSlutDatum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonSokDatum = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TabellHattar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        tfSummaPris = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        KnappSumAntal = new javax.swing.JButton();
        tfSummeraAntal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Telefonnummer");

        jLabel2.setText("Försäljningsstatistik");

        knappSök.setText("Sök");
        knappSök.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knappSökActionPerformed(evt);
            }
        });

        taKundStatistik.setColumns(20);
        taKundStatistik.setRows(5);
        jScrollPane1.setViewportView(taKundStatistik);

        tfStartDatum.setText("ÅÅÅÅ-MM-DD");
        tfStartDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStartDatumActionPerformed(evt);
            }
        });

        tfSlutDatum.setText("ÅÅÅÅ-MM-DD");

        jLabel3.setText("Ange datumintervall");

        buttonSokDatum.setText("Sök");
        buttonSokDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSokDatumActionPerformed(evt);
            }
        });

        TabellHattar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Namn", "OrderID", "Datum", "Pris", "Typ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TabellHattar);

        jButton1.setText("Summera pris");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfSummaPris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSummaPrisActionPerformed(evt);
            }
        });

        jLabel4.setText("1 = Lagerförd & 0 = Anpassad");

        KnappSumAntal.setText("Summera antal");
        KnappSumAntal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnappSumAntalActionPerformed(evt);
            }
        });

        jButton2.setText("Tillbaka");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tfStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfSlutDatum)
                                .addGap(18, 18, 18)
                                .addComponent(buttonSokDatum))
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(knappSök)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KnappSumAntal)
                                .addGap(18, 18, 18)
                                .addComponent(tfSummeraAntal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(tfSummaPris, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(knappSök))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSokDatum)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSummaPris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(KnappSumAntal)
                    .addComponent(tfSummeraAntal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void knappSökActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knappSökActionPerformed
        Connector conn = new Connector();
            // TODO add your handling code here:
    

        //Connector conn = new Connector();
        //mysql Query  to get all the requariment ( articleId,..etc)
        String sql = "Select o.OrderID, a2.Article_Name, o.Datum from `order` as o \n"
                + "join `order_contains_of_article` as a1 on o.OrderId = a1.OrderId\n"
                + "join `article` as a2 on a2.ArticleID = a1.ArticleID\n";
                
        
       

        //
        ArrayList<HashMap<String, String>> result = null;

        try {

            result = conn.idb.fetchRows(sql);
        } catch (InfException ex) {
            Logger.getLogger(PlaneringsYta.class.getName()).log(Level.SEVERE, null, ex);
        }

        String str = "OrderID\tArticleName\tDatum\n";
        for (HashMap<String, String> map : result) {
            str += map.get("OrderID") + "\t" + map.get("Article_Name") + "\t" + map.get("Datum") + "\n";
        }
        taKundStatistik.setText(str);
    }//GEN-LAST:event_knappSökActionPerformed

    private void tfStartDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStartDatumActionPerformed

    }//GEN-LAST:event_tfStartDatumActionPerformed

    private void buttonSokDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSokDatumActionPerformed
 
   try{

            String startDatum = tfStartDatum.getText();
            String slutDatum = tfSlutDatum.getText();

            String sqlFraga = "select Article_Name, OrderID, datum, Price, Article_stocked from `order`, article where datum between '" + startDatum + "' and '" + slutDatum + "'";

            DefaultTableModel dTM = (DefaultTableModel) TabellHattar.getModel();
            dTM.setRowCount(0);

            //Skapa hashmap för att hålla lista på Namn och Registreringsdatum.
        ArrayList<HashMap<String, String>> TabellHattar; // först testa vi bara  HashMap<String, String>, men förslag gav oss istället Arraylist<HashMap<String, String>> som funka.
        TabellHattar = idb.fetchRows(sqlFraga);

        //Loopa igenom datum.
        for(HashMap ettRegDatum : TabellHattar){
                Vector nyLista = new Vector(); //Vi testade först med --> ArrayList nyLista = new ArrayList(); men gav felmedellande. Förslag gav = gör med vector istället. 
                nyLista.add(ettRegDatum.get("Article_Name"));
                nyLista.add(ettRegDatum.get("OrderID"));
                nyLista.add(ettRegDatum.get("datum"));
                nyLista.add(ettRegDatum.get("Price"));
                nyLista.add(ettRegDatum.get("Article_stocked"));
                dTM.addRow(nyLista);
        }
        } catch (InfException undanTag){
        JOptionPane.showMessageDialog(null,"Något fel uppstod");
        System.out.println("Error: " + undanTag);
        }
    

    }//GEN-LAST:event_buttonSokDatumActionPerformed

    private void tfSummaPrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSummaPrisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSummaPrisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
            
            int total = 0;
     for (int i = 0; i < TabellHattar.getRowCount(); i++) {
     total += Integer.parseInt(TabellHattar.getValueAt(i, 3).toString());
  }
     tfSummaPris.setText("Total: " + total);
         
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void KnappSumAntalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnappSumAntalActionPerformed

        int rowCount = TabellHattar.getRowCount();
        tfSummeraAntal.setText(Integer.toString(rowCount));
    }//GEN-LAST:event_KnappSumAntalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FörsäljningsStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FörsäljningsStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FörsäljningsStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FörsäljningsStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FörsäljningsStatistik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KnappSumAntal;
    private javax.swing.JTable TabellHattar;
    private javax.swing.JButton buttonSokDatum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton knappSök;
    private javax.swing.JTextArea taKundStatistik;
    private javax.swing.JTextField tfSlutDatum;
    private javax.swing.JTextField tfStartDatum;
    private javax.swing.JTextField tfSummaPris;
    private javax.swing.JTextField tfSummeraAntal;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
