/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarn;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import oru.inf.InfDB;
import oru.inf.InfException;
import hattmakarn.orderRegister;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author theod
 */
public class RegistreraOrder extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form RegistreraOrder
     */
    public RegistreraOrder() {
        initComponents();
       
          try {
           idb = new InfDB("hattdb", "3306", "hattdba", "hattkey");
        } catch (InfException ex) {
            
        }
          
          fyllcbKundAnpassad();
          fyllcbLagerHatt();
          fyllcbSpecialAnpassad();  
          fyllcbKundAnpassadDekoration1();
          fyllcbKundAnpassadDekoration2();
          fyllcbKundAnpassadDekoration3();
          fyllcbSpecialAnpassadDekoration1();
          fyllcbSpecialAnpassadDekoration2();
          fyllcbSpecialAnpassadDekoration3();
          checkBoxBrodskandeLagerFord();
        
          ValjKund();
          fyllcbAnställda();
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbLagerFord = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfPris = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfArtikelNamnKundAnpassad = new javax.swing.JTextField();
        cbHattypKundAnpassad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbSpecialAnpassadDekoration1 = new javax.swing.JComboBox<>();
        cbKundAnpassadDekoration2 = new javax.swing.JComboBox<>();
        cbKundAnpassadDekoration3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbSpecialAnpassadTyg = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfPrisSpecialAnpassad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfArtikelIDLagerFord = new javax.swing.JTextField();
        cbKundAnpassadDekoration1 = new javax.swing.JComboBox<>();
        cbSpecialAnpassadDekoration2 = new javax.swing.JComboBox<>();
        cbSpecialAnpassadDekoration3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfPrisKundAnpassad1 = new javax.swing.JTextField();
        checkLagerFord = new javax.swing.JCheckBox();
        buttonLagerFord = new javax.swing.JButton();
        buttonKundAnpassad = new javax.swing.JButton();
        buttonSpecialAnpassad = new javax.swing.JButton();
        tfDatum = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfDatum1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfDatum2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        knappBrodskande = new javax.swing.JButton();
        knappBrodskandeSpecial = new javax.swing.JButton();
        checkSpecialAnpassad = new javax.swing.JCheckBox();
        cbValjKund = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BtnRegKund = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tfArtikelNamnSpecialAnpassad = new javax.swing.JTextField();
        cbAnställningsnummer = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        tfDek1 = new javax.swing.JTextField();
        tfDek2 = new javax.swing.JTextField();
        TfDek1 = new javax.swing.JTextField();
        tfDek3 = new javax.swing.JTextField();
        TfDek3 = new javax.swing.JTextField();
        TfDek2 = new javax.swing.JTextField();
        TfTyg = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Lagerförd hatt");

        jButton2.setText("Kundanpassad hatt");

        jButton3.setText("Specialanpassad hatt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbLagerFord.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj hatt" }));
        cbLagerFord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLagerFordActionPerformed(evt);
            }
        });

        jLabel2.setText("Pris");

        tfPris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrisActionPerformed(evt);
            }
        });

        jLabel3.setText("Artikel ID");

        tfArtikelNamnKundAnpassad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfArtikelNamnKundAnpassadActionPerformed(evt);
            }
        });

        cbHattypKundAnpassad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj hatt" }));
        cbHattypKundAnpassad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHattypKundAnpassadActionPerformed(evt);
            }
        });

        jLabel4.setText("Välj lagerförd hatt");

        jLabel5.setText("Välj lagerförd hatt");

        cbSpecialAnpassadDekoration1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj dekoration" }));

        cbKundAnpassadDekoration2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj dekoration" }));
        cbKundAnpassadDekoration2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKundAnpassadDekoration2ActionPerformed(evt);
            }
        });

        cbKundAnpassadDekoration3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj dekoration" }));

        jLabel6.setText("Dekoration 1");

        jLabel7.setText("Dekoration 3");

        jLabel8.setText("Dekoration 2");

        cbSpecialAnpassadTyg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj tyg" }));

        jLabel9.setText("Tyg");

        jLabel10.setText("Pris");

        jLabel11.setText("Artikelnamn");

        tfArtikelIDLagerFord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfArtikelIDLagerFordActionPerformed(evt);
            }
        });

        cbKundAnpassadDekoration1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj dekoration", "Band", "Strutsfjäder", "Påfågerfjäder", "Hönsfjäder", "Tygblomma", "Pärlor", "Spetts", "Lackeratpapper", "Lurextråd", "Fuskpäls" }));
        cbKundAnpassadDekoration1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKundAnpassadDekoration1ActionPerformed(evt);
            }
        });

        cbSpecialAnpassadDekoration2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj dekoration" }));

        cbSpecialAnpassadDekoration3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj dekoration" }));

        jLabel13.setText("Dekoration 1");

        jLabel14.setText("Dekoration 2");

        jLabel15.setText("Dekoration 3");

        jLabel17.setText("Pris");

        checkLagerFord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLagerFordActionPerformed(evt);
            }
        });

        buttonLagerFord.setText("Lägg till");
        buttonLagerFord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLagerFordActionPerformed(evt);
            }
        });

        buttonKundAnpassad.setText("Lägg till");
        buttonKundAnpassad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKundAnpassadActionPerformed(evt);
            }
        });

        buttonSpecialAnpassad.setText("Lägg till");
        buttonSpecialAnpassad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSpecialAnpassadActionPerformed(evt);
            }
        });

        jLabel19.setText("Datum:");

        jLabel20.setText("Datum:");

        jLabel21.setText("Datum:");

        knappBrodskande.setText("Brådskande");
        knappBrodskande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knappBrodskandeActionPerformed(evt);
            }
        });

        knappBrodskandeSpecial.setText("Brådskande");
        knappBrodskandeSpecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knappBrodskandeSpecialActionPerformed(evt);
            }
        });

        checkSpecialAnpassad.setText("jCheckBox1");

        cbValjKund.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj kund" }));
        cbValjKund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValjKundActionPerformed(evt);
            }
        });

        jLabel1.setText("Välj befintlig kund");

        BtnRegKund.setText("Skapa ny kund");
        BtnRegKund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegKundActionPerformed(evt);
            }
        });

        jButton4.setText("Tillbaka");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("Arikelnamn");

        cbAnställningsnummer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj personal" }));
        cbAnställningsnummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnställningsnummerActionPerformed(evt);
            }
        });

        jLabel16.setText("Välj personal");

        TfDek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfDek1ActionPerformed(evt);
            }
        });

        jLabel18.setText("st");

        jLabel22.setText("st");

        jLabel23.setText("st");

        jLabel24.setText("st");

        jLabel25.setText("st");

        jLabel26.setText("st");

        jLabel27.setText("meter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPris, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfArtikelIDLagerFord, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonLagerFord)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfDatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                            .addComponent(cbValjKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbLagerFord, 0, 116, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(cbHattypKundAnpassad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfDatum1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfPrisKundAnpassad1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkLagerFord, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(knappBrodskande)))
                                .addGap(77, 77, 77))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbKundAnpassadDekoration3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbKundAnpassadDekoration2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfDek3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                                            .addComponent(tfDek2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbKundAnpassadDekoration1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfDek1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbAnställningsnummer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(84, 84, 84))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfArtikelNamnSpecialAnpassad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonSpecialAnpassad))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfDatum2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(checkSpecialAnpassad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(knappBrodskandeSpecial))
                                            .addComponent(tfPrisSpecialAnpassad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbSpecialAnpassadDekoration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TfDek1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbSpecialAnpassadDekoration3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TfDek3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbSpecialAnpassadDekoration2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TfDek2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbSpecialAnpassadTyg, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TfTyg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel27)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonKundAnpassad)
                            .addComponent(tfArtikelNamnKundAnpassad, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(BtnRegKund))
                .addContainerGap(656, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSpecialAnpassadDekoration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfDek1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKundAnpassadDekoration2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSpecialAnpassadDekoration2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDek2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfDek2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKundAnpassadDekoration3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSpecialAnpassadDekoration3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDek3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfDek3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbLagerFord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbHattypKundAnpassad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSpecialAnpassadTyg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfTyg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKundAnpassadDekoration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDek1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDatum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrisKundAnpassad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrisSpecialAnpassad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkLagerFord, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(knappBrodskande)
                        .addComponent(knappBrodskandeSpecial)
                        .addComponent(checkSpecialAnpassad)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfArtikelIDLagerFord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfArtikelNamnKundAnpassad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfArtikelNamnSpecialAnpassad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLagerFord)
                    .addComponent(buttonKundAnpassad)
                    .addComponent(buttonSpecialAnpassad))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbValjKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAnställningsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnRegKund)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbLagerFordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLagerFordActionPerformed
    // TODO add your handling code here:
    //valdLagerFord = cbLagerFord.getSelectedItem().toString();
    }//GEN-LAST:event_cbLagerFordActionPerformed
    private void fyllcbLagerHatt(){ //Fylla 
            String fraga = "SELECT Article_Name FROM article where Article_stocked = 1";
          
        ArrayList<String> LagerFordaHattar;
        try {
            LagerFordaHattar = idb.fetchColumn(fraga);

            for (String lagerHatt : LagerFordaHattar) {
                cbLagerFord.addItem(lagerHatt);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    } 
        cbLagerFord.addItemListener(new ItemListener()
          {
               public void itemStateChanged(ItemEvent event)
               {
                    if (event.getStateChange() == ItemEvent.SELECTED)
                    {
                         try
                         {
                             String valdHatt = cbLagerFord.getSelectedItem().toString();
                              String no = "select Price from article where Article_Name = '"+ valdHatt + "'";
                              String answer = idb.fetchSingle(no);
                              tfPris.setText(answer);
                         }
                         catch (Exception ex)
                         {
                              ex.printStackTrace();
                         }
                    }
               }
        }
        );
        cbLagerFord.addItemListener(new ItemListener()
          {
               public void itemStateChanged(ItemEvent event)
               {
                    if (event.getStateChange() == ItemEvent.SELECTED)
                    {
                         try
                         {
                             String valdHatt = cbLagerFord.getSelectedItem().toString();
                              String no = "select ArticleID from article where Article_Name = '"+ valdHatt + "'";
                              String answer = idb.fetchSingle(no);
                              tfArtikelIDLagerFord.setText(answer);
                         }
                         catch (Exception ex)
                         {
                              ex.printStackTrace();
                         }
                    }
               }
        }
        );
                }
        
    private void fyllcbKundAnpassad(){ //Fylla 
            String fraga = "SELECT Article_Name FROM article where Article_stocked = 1";
          
        ArrayList<String> LagerFordaHattar;
        try {
            LagerFordaHattar = idb.fetchColumn(fraga);

            for (String lagerHatt : LagerFordaHattar) {
                cbHattypKundAnpassad.addItem(lagerHatt);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    } 
        cbHattypKundAnpassad.addItemListener(new ItemListener()
          {
               public void itemStateChanged(ItemEvent event)
               {
                    if (event.getStateChange() == ItemEvent.SELECTED)
                    {
                         try
                         {
                             String valdHatt = cbHattypKundAnpassad.getSelectedItem().toString();
                              String no = "select Price from article where Article_Name = '"+ valdHatt + "'";
                              String answer = idb.fetchSingle(no);
                              tfPrisKundAnpassad1.setText(answer);
                         }
                         catch (Exception ex)
                         {
                              ex.printStackTrace();
                         }
                    }
               }
        }
        );        
        }
    private void fyllcbSpecialAnpassad(){ //Fylla 
            String fraga = "SELECT Material_Name FROM material where Type = 'Bas';";
          
        ArrayList<String> MatrialTyger;
        try {
            MatrialTyger = idb.fetchColumn(fraga);

            for (String lagerHatt : MatrialTyger) {
                cbSpecialAnpassadTyg.addItem(lagerHatt);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    } 
    }
    private void fyllcbKundAnpassadDekoration1() {
        String fraga = "SELECT Material_Name FROM material where Type = 'Dekoration';";

        ArrayList<String> MatrialDekoration;
        try {
            MatrialDekoration = idb.fetchColumn(fraga);

            for (String lagerHatt : MatrialDekoration) {
                cbKundAnpassadDekoration1.addItem(lagerHatt);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    } 

    }
    private void fyllcbKundAnpassadDekoration2() {
        String fraga = "SELECT Material_Name FROM material where Type = 'Dekoration';";

        ArrayList<String> MatrialDekoration;
        try {
            MatrialDekoration = idb.fetchColumn(fraga);

            for (String lagerHatt : MatrialDekoration) {
                cbKundAnpassadDekoration2.addItem(lagerHatt);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    } 

    }
    private void fyllcbKundAnpassadDekoration3() {
        String fraga = "SELECT Material_Name FROM material where Type = 'Dekoration';";

        ArrayList<String> MatrialDekoration;
        try {
            MatrialDekoration = idb.fetchColumn(fraga);

            for (String lagerHatt : MatrialDekoration) {
                cbKundAnpassadDekoration3.addItem(lagerHatt);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    } 

    }
private void fyllcbSpecialAnpassadDekoration1() {
        String fraga = "SELECT Material_Name FROM material where Type = 'Dekoration';";

        ArrayList<String> MatrialDekoration;
        try {
            MatrialDekoration = idb.fetchColumn(fraga);

            for (String lagerHatt : MatrialDekoration) {
                cbSpecialAnpassadDekoration1.addItem(lagerHatt);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    } 

    }
    private void fyllcbSpecialAnpassadDekoration2() {
        String fraga = "SELECT Material_Name FROM material where Type = 'Dekoration';";

        ArrayList<String> MatrialDekoration;
        try {
            MatrialDekoration = idb.fetchColumn(fraga);

            for (String lagerHatt : MatrialDekoration) {
                cbSpecialAnpassadDekoration2.addItem(lagerHatt);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    } 

    }
    private void fyllcbSpecialAnpassadDekoration3() {
        String fraga = "SELECT Material_Name FROM material where Type = 'Dekoration';";

        ArrayList<String> MatrialDekoration;
        try {
            MatrialDekoration = idb.fetchColumn(fraga);

            for (String lagerHatt : MatrialDekoration) {
                cbSpecialAnpassadDekoration3.addItem(lagerHatt);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    } 

    }
    
    private void fyllcbAnställda(){
    String q = "SELECT Name FROM Employee;";

        ArrayList<String> Employees;
        try {
            Employees = idb.fetchColumn(q);

            for (String employ : Employees) {
                cbAnställningsnummer.addItem(employ);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    }}
    private void tfArtikelNamnKundAnpassadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfArtikelNamnKundAnpassadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfArtikelNamnKundAnpassadActionPerformed

    private void tfArtikelIDLagerFordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfArtikelIDLagerFordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfArtikelIDLagerFordActionPerformed

    private void buttonKundAnpassadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKundAnpassadActionPerformed
     try{
        String artikelNamnKundAnpassad = tfArtikelNamnKundAnpassad.getText();
       String datumKundAnpassad = tfDatum1.getText();
       String prisKundAnpassad = tfPrisKundAnpassad1.getText();
       String dekorationKundAnpassad1 = cbKundAnpassadDekoration1.getSelectedItem().toString();
       String dekorationKundAnpassad2 = cbKundAnpassadDekoration2.getSelectedItem().toString();
       String dekorationKundAnpassad3 = cbKundAnpassadDekoration3.getSelectedItem().toString();
       String kundRegister = cbValjKund.getSelectedItem().toString();
       String creator = cbAnställningsnummer.getSelectedItem().toString();
       String amount1 = tfDek1.getText();
       String amount2 = tfDek2.getText();
       String amount3 = tfDek3.getText();
       
       
       String creatorID = "select EmployeeID from Employee where name = '" + creator + "'";
       String getCreatorID = idb.fetchSingle(creatorID);
       String custID = "select CustomerID from Customer where name = '" + kundRegister + "'";
       String getCustID = idb.fetchSingle(custID);
       String artID = "select articleID from article where article_name = '" + artikelNamnKundAnpassad + "'";
       String getArtID = idb.fetchSingle(artID);
       String materialID1 = "select materialID from material where material_name = '" + dekorationKundAnpassad1 + "'";
       String getmaterialID1 = idb.fetchSingle(materialID1);
       String materialID2 = "select materialID from material where material_name = '" + dekorationKundAnpassad2 + "'";
       String getmaterialID2 = idb.fetchSingle(materialID2);
       String materialID3 = "select materialID from material where material_name = '" + dekorationKundAnpassad3 + "'";
       String getmaterialID3 = idb.fetchSingle(materialID3);
       
       String insertarticle = "insert into Article (Article_name, price, article_stocked) values ('" + artikelNamnKundAnpassad + "'," + prisKundAnpassad + "," + false + ")";
    idb.insert(insertarticle);
    
     String lastAID = "select max(ArticleID) from article";
      String getLastAID = idb.fetchSingle(lastAID);
      
    
    
    String insertarticle_contains_of_material1 = "insert into Article_contains_of_material values (" + getLastAID + "," + getmaterialID1 + "," + amount1 + "),(" + getLastAID + "," + getmaterialID2 + "," + amount2 + "),(" + getLastAID + "," + getmaterialID3 + "," + amount3 + ")";
    idb.insert(insertarticle_contains_of_material1);
 
   
    String insertOrder = "insert into `Order` (Datum, EmployeeID, CustomerID) values ('" + datumKundAnpassad + "'," + getCreatorID + "," + getCustID + ")";
    idb.insert(insertOrder);
       
      String lastID = "select max(orderID) from `Order`";
      String getLastID = idb.fetchSingle(lastID);
       
     String insertOrderArticle = "insert into order_contains_of_article values (" + getLastID + "," + getLastAID + ")";
       
      idb.insert(insertOrderArticle);
      
      String insertProduction = "insert into production (Status, ArticleID, OrderID) values ('Lagd'," + getLastAID + "," + getLastID + ")";
    idb.insert(insertProduction);
      
    
    JOptionPane.showMessageDialog(null, "Din order har skapats");
       
     } catch(InfException ex){
        System.out.println(ex.getMessage());}
    }//GEN-LAST:event_buttonKundAnpassadActionPerformed

    private void buttonLagerFordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLagerFordActionPerformed

        try{
       String artikelLagerFord = cbLagerFord.getSelectedItem().toString();
       String datumLagerFord = tfDatum.getText();
       String prisLagerFord = tfPris.getText();
       String kundRegister = cbValjKund.getSelectedItem().toString();
       String creator = cbAnställningsnummer.getSelectedItem().toString();
       
       String creatorID = "select EmployeeID from Employee where name = '" + creator + "'";
       String getCreatorID = idb.fetchSingle(creatorID);
       String custID = "select CustomerID from Customer where name = '" + kundRegister + "'";
       String getCustID = idb.fetchSingle(custID);
       String artID = "select articleID from article where article_name = '" + artikelLagerFord + "'";
       String getArtID = idb.fetchSingle(artID);
      
      String insertOrder = "insert into `Order` (Datum, EmployeeID, CustomerID) values ('" + datumLagerFord + "'," + getCreatorID + "," + getCustID + ")";
    idb.insert(insertOrder);
       
      String lastID = "select max(orderID) from `Order`";
      String getLastID = idb.fetchSingle(lastID);
       
     String insertOrderArticle = "insert into order_contains_of_article values (" + getLastID + "," + getArtID + ")";
       
      idb.insert(insertOrderArticle);
      JOptionPane.showMessageDialog(null, "Din order har skapats");
       }
        
        catch(InfException ex){
        System.out.println(ex.getMessage());}
       
       
    }//GEN-LAST:event_buttonLagerFordActionPerformed

    private void cbKundAnpassadDekoration1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKundAnpassadDekoration1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKundAnpassadDekoration1ActionPerformed

    private void tfPrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrisActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfPrisActionPerformed

    private void checkBoxBrodskandeLagerFord ()
    {
                try{
        String item = cbLagerFord.getSelectedItem().toString();
        String fraga = "select Price from article where Article_Name = '"+ item +"'";
        String svar = idb.fetchSingle(fraga);
        //String pris = tfPris.getText();
        if(checkLagerFord.isSelected()) {
            double num = Double.parseDouble(svar);
            double result = num * 1.2;
            String num1 = Double.toString(result);
           tfPris.setText(num1);
        }
        } catch (InfException e) {
        }
    }
    
    private void checkLagerFordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLagerFordActionPerformed

    }//GEN-LAST:event_checkLagerFordActionPerformed

    private void knappBrodskandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knappBrodskandeActionPerformed
        // TODO add your handling code here:
        try{
        String item = cbHattypKundAnpassad.getSelectedItem().toString();
        String fraga = "select Price from article where Article_Name = '"+ item +"'";
        String svar = idb.fetchSingle(fraga);
        //String pris = tfPris.getText();
        checkLagerFord.setSelected(rootPaneCheckingEnabled);
            double num = Double.parseDouble(svar);
            double result = num * 1.2;
            String num1 = Double.toString(result);
           tfPrisKundAnpassad1.setText(num1);
       
        } catch (InfException e) {
        }
    }//GEN-LAST:event_knappBrodskandeActionPerformed

    private void knappBrodskandeSpecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knappBrodskandeSpecialActionPerformed
        // TODO add your handling code here:
        try{
        String item = cbHattypKundAnpassad.getSelectedItem().toString();
        String fraga = "select Price from article where Article_Name = '"+ item +"'";
        String svar = idb.fetchSingle(fraga);
        String pris = tfPrisSpecialAnpassad.getText();
        checkSpecialAnpassad.setSelected(rootPaneCheckingEnabled);
            double num = Double.parseDouble(pris);
            double result = num * 1.2;
            String num1 = Double.toString(result);
           tfPrisSpecialAnpassad.setText(num1);
       
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }
    }//GEN-LAST:event_knappBrodskandeSpecialActionPerformed

    private void cbValjKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValjKundActionPerformed


    }//GEN-LAST:event_cbValjKundActionPerformed

    private void ValjKund() {
        String fraga = "SELECT Name FROM customer;";

        ArrayList<String> kundRegister;
        try {
            kundRegister = idb.fetchColumn(fraga);

            for (String kund : kundRegister) {
                cbValjKund.addItem(kund);
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
    } 
    }
    private void cbKundAnpassadDekoration2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKundAnpassadDekoration2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKundAnpassadDekoration2ActionPerformed

    private void BtnRegKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegKundActionPerformed
        new RegistreraKund().setVisible(true);
    }//GEN-LAST:event_BtnRegKundActionPerformed

   
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void buttonSpecialAnpassadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSpecialAnpassadActionPerformed
       try{
        String datumSpecialAnpassad = tfDatum2.getText();
       String prisSpecialAnpassad = tfPrisSpecialAnpassad.getText();
       String artikelNamnSpecialAnpassad = tfArtikelNamnSpecialAnpassad.getText();
       String specialAnpassadTyg = cbSpecialAnpassadTyg.getSelectedItem().toString();
       String dekorationSpecialAnpassad1 = cbSpecialAnpassadDekoration1.getSelectedItem().toString();
       String dekorationSpecialAnpassad2 = cbSpecialAnpassadDekoration2.getSelectedItem().toString();
       String dekorationSpecialAnpassad3 = cbSpecialAnpassadDekoration3.getSelectedItem().toString();
       String kundRegister = cbValjKund.getSelectedItem().toString();
       String creator = cbAnställningsnummer.getSelectedItem().toString();
       
       String sAmount1 = TfTyg.getText();
       String sAmount2 = TfDek1.getText();
       String sAmount3 = TfDek2.getText();
       String sAmount4 = TfDek3.getText();
       
       String creatorID = "select EmployeeID from Employee where name = '" + creator + "'";
       String getCreatorID = idb.fetchSingle(creatorID);
       String custID = "select CustomerID from Customer where name = '" + kundRegister + "'";
       String getCustID = idb.fetchSingle(custID);
       String artID = "select articleID from article where article_name = '" + artikelNamnSpecialAnpassad + "'";
       String getArtID = idb.fetchSingle(artID);
       String tygID = "select materialID from material where material_name = '" + specialAnpassadTyg + "'";
       String getTygID = idb.fetchSingle(tygID);
       String materialID1 = "select materialID from material where material_name = '" + dekorationSpecialAnpassad1 + "'";
       String getmaterialID1 = idb.fetchSingle(materialID1);
       String materialID2 = "select materialID from material where material_name = '" + dekorationSpecialAnpassad2 + "'";
       String getmaterialID2 = idb.fetchSingle(materialID2);
       String materialID3 = "select materialID from material where material_name = '" + dekorationSpecialAnpassad3 + "'";
       String getmaterialID3 = idb.fetchSingle(materialID3);
       
       String insertarticle = "insert into Article (Article_name, price, article_stocked) values ('" + artikelNamnSpecialAnpassad + "'," + prisSpecialAnpassad + "," + false + ")";
    idb.insert(insertarticle);
    
     String lastAID = "select max(ArticleID) from article";
      String getLastAID = idb.fetchSingle(lastAID);
      
       String insertarticle_contains_of_material0 = "insert into Article_contains_of_material values (" + getLastAID + "," + getTygID + "," + sAmount1 + "),(" + getLastAID + "," + getmaterialID1 + "," + sAmount2 + "),(" + getLastAID + "," + getmaterialID2 + "," + sAmount3 + "),(" + getLastAID + "," + getmaterialID3 + "," + sAmount4 + ")";
    idb.insert(insertarticle_contains_of_material0);
    

   
    String insertOrder = "insert into `Order` (Datum, EmployeeID, CustomerID) values ('" + datumSpecialAnpassad + "'," + getCreatorID + "," + getCustID + ")";
    idb.insert(insertOrder);
       
      String lastID = "select max(orderID) from `Order`";
      String getLastID = idb.fetchSingle(lastID);
       
     String insertOrderArticle = "insert into order_contains_of_article values (" + getLastID + "," + getLastAID + ")";
       
      idb.insert(insertOrderArticle);
      
      String insertProduction = "insert into production (Status, ArticleID, OrderID) values ('Lagd'," + getLastAID + "," + getLastID + ")";
    idb.insert(insertProduction);
      
    
    JOptionPane.showMessageDialog(null, "Din order har skapats");
       
     } catch(InfException ex){
        System.out.println(ex.getMessage());}
    }//GEN-LAST:event_buttonSpecialAnpassadActionPerformed

    private void cbAnställningsnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnställningsnummerActionPerformed
         
   
    

    }//GEN-LAST:event_cbAnställningsnummerActionPerformed

    private void cbHattypKundAnpassadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHattypKundAnpassadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHattypKundAnpassadActionPerformed

    private void TfDek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfDek1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfDek1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreraOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreraOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreraOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreraOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistreraOrder().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegKund;
    private javax.swing.JTextField TfDek1;
    private javax.swing.JTextField TfDek2;
    private javax.swing.JTextField TfDek3;
    private javax.swing.JTextField TfTyg;
    private javax.swing.JButton buttonKundAnpassad;
    private javax.swing.JButton buttonLagerFord;
    private javax.swing.JButton buttonSpecialAnpassad;
    private javax.swing.JComboBox<String> cbAnställningsnummer;
    private javax.swing.JComboBox<String> cbHattypKundAnpassad;
    private javax.swing.JComboBox<String> cbKundAnpassadDekoration1;
    private javax.swing.JComboBox<String> cbKundAnpassadDekoration2;
    private javax.swing.JComboBox<String> cbKundAnpassadDekoration3;
    private javax.swing.JComboBox<String> cbLagerFord;
    private javax.swing.JComboBox<String> cbSpecialAnpassadDekoration1;
    private javax.swing.JComboBox<String> cbSpecialAnpassadDekoration2;
    private javax.swing.JComboBox<String> cbSpecialAnpassadDekoration3;
    private javax.swing.JComboBox<String> cbSpecialAnpassadTyg;
    private javax.swing.JComboBox<String> cbValjKund;
    private javax.swing.JCheckBox checkLagerFord;
    private javax.swing.JCheckBox checkSpecialAnpassad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton knappBrodskande;
    private javax.swing.JButton knappBrodskandeSpecial;
    private javax.swing.JTextField tfArtikelIDLagerFord;
    private javax.swing.JTextField tfArtikelNamnKundAnpassad;
    private javax.swing.JTextField tfArtikelNamnSpecialAnpassad;
    private javax.swing.JTextField tfDatum;
    private javax.swing.JTextField tfDatum1;
    private javax.swing.JTextField tfDatum2;
    private javax.swing.JTextField tfDek1;
    private javax.swing.JTextField tfDek2;
    private javax.swing.JTextField tfDek3;
    private javax.swing.JTextField tfPris;
    private javax.swing.JTextField tfPrisKundAnpassad1;
    private javax.swing.JTextField tfPrisSpecialAnpassad;
    // End of variables declaration//GEN-END:variables
}
