/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarn;

import java.util.ArrayList; 
import oru.inf.InfDB; 
import oru.inf.InfException; 
import javax.swing.JOptionPane;
/**
 *
 * @author clarajonsson
 */
public class SokArtikel extends javax.swing.JFrame {
private static InfDB idb;
    /**
     * Creates new form SokArtikel
     */
    public SokArtikel() {
        initComponents();
        try{
            idb = new InfDB("hattdb", "3306", "hattdba", "hattkey");
        }catch (InfException ex){
            
        }
         fyllBoxMedArtikelnamn();
    }
    
    
    
    private void fyllBoxMedArtikelnamn() {
        
        String fraga = "Select Article_Name from article";
        
        ArrayList<String> article;
        
        try{
            article = idb.fetchColumn(fraga);
            
            for(String articleName : article){
                sokArtikelBox.addItem(articleName);
            }
        }catch (InfException e){
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sokArtikelBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Sök artikel");

        jLabel2.setText("Sök artikelnamn:");

        sokArtikelBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokArtikelBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Välj artikel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sokArtikelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton1)))

                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sokArtikelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))

                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sokArtikelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sokArtikelBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokArtikelBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sokArtikelBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
            
        
        
        String articleName = sokArtikelBox.getSelectedItem().toString();
        String articleID = idb.fetchSingle( "Select ArticleID from article where Article_Name = '" + articleName + "'");
        String name = idb.fetchSingle( "Select Article_Name from article where Article_Name = '" + articleName + "'");
        String price = idb.fetchSingle( "Select Price from article where Article_Name = '" + articleName + "'");
        String articleStocked = idb.fetchSingle( "Select Article_stocked from article where Article_Name = '" + articleName + "'");
        
       JOptionPane.showMessageDialog(null, "ID: " + articleID + "\nArtikelnamn: " + name + "\nPris: " + price + "\nLagerförd artikel: " + articleStocked + "" );
        





//ArrayList<String> articles = idb.fetchColumn(showArticleID);
        
//        for(String thisArticle : articles){
//            articleT.append(thisArticle);
//            articleT.append(" \n");
//        }
//            
//            
//         
//        String showArticleName = "Select Article_Name, ArticleID, Price, Article_stocked from article where Article_Name = '" + articleName + "'";
//        ArrayList<String> name = idb.fetchColumn(showArticleName);
//        
//        for(String thisName : name){
//            articleT.append(thisName);
//            articleT.append(" \n");
            
        
            
//            String articleName = sokArtikelBox.getSelectedItem().toString();
//        String showArticle = "Select ArticleID, Article_Name, Price, Article_stocked from article where Article_Name = '" + articleName + "'";
//        ArrayList<String> articles = idb.fetchColumn(showArticle);
//        
//        for(String thisArticle : articles){
//            articleT.append(thisArticle);
//            articleT.append(" \n");
//            
            
            
            
            
        
        
        }catch(InfException a){
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SokArtikel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SokArtikel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SokArtikel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SokArtikel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SokArtikel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> sokArtikelBox;
    // End of variables declaration//GEN-END:variables
}
